theme: jekyll-theme-minimal
title: Levi's Site

#Welcome to my page!

The purpose of this pages is to create a site to showcase my resume and projects as well as trying to inform a little slice of the internet of the dangers of Cyber threats.

##This page is currently under construction, please feel free visit any time as changes will be made frequently!
